apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-port-deployment
  labels:
    app: multi-port-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-port-app
  template:
    metadata:
      labels:
        app: multi-port-app
    spec:
      containers:
      - name: app
        image: httpd:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
