apiVersion: v1
kind: pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name : nginx-pod-test
      image : nginx:latest
      volumeMounts:
      - name: test-mount
        mountPath: "/etc/non-sensitive-data"
        readOnly: true
  volumes :
   - name: test-mount
     ConfigMap:



# kubectl create configmap nginx-cm  --from-file=file1.txt --from-file-file2.txt


